# Generated by Django 5.2.7 on 2025-10-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_usertest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTest',
        ),
    ]
